### ISSUE TITLE
TestFlight Beta Expired

### ISSUE THREAD

**Issue by gamersi** [TheNoim/project-sitnu#10]
It would be nice when you could create a new link. Alternatively I would be willing to give you my login data for the purpose of apple reviewing it for the AppStore. But I will ask my headmaster if they could create a account in order that they could these it with a test account
Greetings
gamersi

**Comment by TheNoim** [comment]
I now submitted a new TestFlight Beta. It can take a few hours until it gets approved. I am very sorry that this toke so long, but I was simply busy. 

> Alternatively I would be willing to give you my login data for the purpose of apple reviewing it for the AppStore. But I will ask my headmaster if they could create a account in order that they could these it with a test account

This would be awesome! I would still need to create promotional pictures for the app store with anonymized/demo data.
