### ISSUE TITLE
Unknown WebUntis error

### ISSUE THREAD

**Issue by bifaciall** [TheNoim/project-sitnu#14]
![IMG_7904](https://user-images.githubusercontent.com/83917104/199767084-9b7398c5-5807-4ab0-8517-1558cdbcd45d.PNG)

It says it is an unknown error, which isnt very helpful... any ideas why that is.
obviously I downloaded it in testflight etc..

**Comment by rottifant** [comment]
I assume that the problem has to do with the school name you entered.
You entered the name that is displayed on the page but i think you have to enter the name which is also used in the URL:
![grafik](https://user-images.githubusercontent.com/78685408/200146543-6fa30d45-99f2-47e7-b3b2-0441e143ad74.png)
So I would suggest you to try it again with "FSG Ludwigsburg". (without the plus here)

**Comment by TheNoim** [comment]
> I assume that the problem has to do with the school name you entered. You entered the name that is displayed on the page but i think you have to enter the name which is also used in the URL: ![grafik](https://user-images.githubusercontent.com/78685408/200146543-6fa30d45-99f2-47e7-b3b2-0441e143ad74.png) So I would suggest you to try it again with "FSG Ludwigsburg". (without the plus here)

This is probably it.

**Comment by bifaciall** [comment]
Yep that was it. Thanks
