### ISSUE TITLE
Timetable doesnt show anything

### ISSUE THREAD

**Issue by bifaciall** [TheNoim/project-sitnu#15]
I got it working but it says that there are no classes whatsoever

**Comment by TheNoim** [comment]
Hi,

I am aware of this issue. However, do to a combination of being ill, lack of time and issues with my apple watch, I need more time to look into it.

**Comment by bifaciall** [comment]
> Hi,
> 
> 
> 
> I am aware of this issue. However, do to a combination of being ill, lack of time and issues with my apple watch, I need more time to look into it. 

No problem; take your time im not depending on it :)

**Comment by TheNoim** [comment]
You can try the new build.

**Comment by bifaciall** [comment]
Just forgot to close; works now :)

**Comment by bifaciall** [comment]
But there is an equal sign before the class and the room is bugged out

**Comment by bifaciall** [comment]
![image](https://user-images.githubusercontent.com/83917104/204051664-1fd31092-eb0a-4a31-b1b0-d849b71334c0.jpeg)
