### ISSUE TITLE
Idea/Suggestion :)

### ISSUE THREAD

**Issue by bifaciall** [TheNoim/project-sitnu#26]
I have some subjects that are paralellel so: some ppl have spanish, some habe cs. I would like them to be next to each other like shown in the picture. Or if its possible: select what subjects to show or not to show in the app. ![image](https://github.com/TheNoim/project-sitnu/assets/83917104/69681335-19f4-478e-8b4b-d1d680b1bfaf)

And this is what it looks like right now in the sitnu watchapp:
![image](https://github.com/TheNoim/project-sitnu/assets/83917104/e3da9f99-8b0b-4418-aedc-fdce7455f0c4)
![image](https://github.com/TheNoim/project-sitnu/assets/83917104/8e5959e5-2b10-444f-9062-5342f77401a9)

So to clarify: in the 2nd/3rd picture its below each other and i want it to be besides each ither like in the official app(1st picture). Or as i said to be able to select what subject to show or not to show. :)
Do it when you have time. Best wishes David

**Comment by bifaciall** [comment]
Also: when something is cancelled I would like it to be shown side by side as well. Time can be as is: under both at the same time because its parallel. 😃

**Comment by bifaciall** [comment]
+ would it be possible to put the room of the subject under the subject rather than the time? (As a toggle option in settings)

**Comment by TheNoim** [comment]
I think, the screen on the apple watch is not really wide enough to put lessons in parallel. 

> would it be possible to put the room of the subject under the subject rather than the time? (As a toggle option in settings)

I added this option in: https://github.com/TheNoim/project-sitnu/commit/46c744664da51acdd2643bd8830a99003cb9129f

**Comment by bifaciall** [comment]
Thx

**Comment by bifaciall** [comment]
My idea with putting it next to each other is kinda obsolete cause my school made so that one only sees the courses they have.
