### ISSUE TITLE
Bug when clicking on a lesson

### ISSUE THREAD

**Issue by tschuerti** [TheNoim/project-sitnu#28]
If you click on a lesson, nothing is displayed, under WatchOS 9 you could go back via the Digital Crown and click again, then it worked. This is now a problem under WatchOS 10, because you can no longer go back via the Digital Crown. So it's not possible to see the details of an lesson. I don't know if this is only a bug on my Watch (Series 8) or a general one.

**Comment by TheNoim** [comment]
Next week I have some spare time. I will look into it. I remember there was a SwiftUI bug with no workaround. Hopefully, there is one now.

**Comment by tschuerti** [comment]
Thanks🙏
