### ISSUE TITLE
Cannot add Untis Account 

### ISSUE THREAD

**Issue by JMcrafter26** [TheNoim/project-sitnu#29]
Like the title says, I cannot add an Untis account. The plus (+) is just grey and not clickable. 

![IMG_8817](https://github.com/TheNoim/project-sitnu/assets/77780772/c0cf0a41-daf8-437a-8a08-d0cd13ebd2a6)

**Comment by TheNoim** [comment]
Watch Connectivity is a bit tricky. Just reopen the apple watch a bunch of times. I am already working on a way to fix this, but this is far away from ready.
