### ISSUE TITLE
Got removed from TestFlight 

### ISSUE THREAD

**Issue by JMcrafter26** [TheNoim/project-sitnu#32]
Hi there, I noticed that I got removed from the TestFlight app and can’t join. As I use the app almost daily, this is not very optimal for me.
Please could you add me again?

**Comment by MaiS28** [comment]
I have the same problem. The app is really usefull and I use it daily so I would really like to could use it again.

**Comment by TheNoim** [comment]
Testflight probably expired. Soon I resubmit

**Comment by TheNoim** [comment]
New build available. 

I will probably look into distribution via the recently launched [altstore](https://altstore.io/).
