### ISSUE TITLE
Url is not valid

### ISSUE THREAD

**Issue by hugo1887** [TheNoim/project-sitnu#4]
I think it's because my school-name has an space(" ") in it so the app doesn't work. how can I fix this?

**Comment by TheNoim** [comment]
Yes, this should be fixable. You can try replacing the space with %20 manual until I fix this.

**Comment by TheNoim** [comment]
Have you tried it?

**Comment by hugo1887** [comment]
> Have you tried it?

sorry for this long time waiting! I can't edit the schools name :(

**Comment by hugo1887** [comment]
> Yes, this should be fixable. You can try replacing the space with %20 manual until I fix this. 

where I can replace the space?
when I do this in searchbar my school is not listed anymore. And in the login data fields I can't correct/replace this.

**Comment by TheNoim** [comment]
Can you send me an E-Mail with the school name and maybe even some kind of login data? Then I will try to fix it. I mean, I can make the school field editable, but I can't say anything to why your school isn't listed anymore.

**Comment by hugo1887** [comment]
what do you mean by login data?
because I don't want to give you my password :) Or you mean name?

**Comment by hugo1887** [comment]
Are you German? Because on your website you say something about germany forces you to have an Imprint

**Comment by TheNoim** [comment]
> what do you mean by login data?
> because I don't want to give you my password :) Or you mean name?

Yes, I meant both username and pw. But it is completely understandable if you don't want to send your login data to someone unknown. However, if you want me to find out why your school isn't working, I need some way to debug it. Does your school support anonymous login? Maybe the school name could help. 

> Are you German? Because on your website you say something about germany forces you to have an Imprint

Yes

**Comment by hugo1887** [comment]
> > what do you mean by login data?
> 
> > because I don't want to give you my password :) Or you mean name?
> 
> 
> 
> Yes, I meant both username and pw. But it is completely understandable if you don't want to send your login data to someone unknown. However, if you want me to find out why your school isn't working, I need some way to debug it. Does your school support anonymous login? Maybe the school name could help. 
> 
> 
> 
> > Are you German? Because on your website you say something about germany forces you to have an Imprint
> 
> 
> 
> Yes

I send you an eMail. The Mail comes from ...@gmx.de! Thank you for your help!
