### ISSUE TITLE
Releases IPAs

### ISSUE THREAD

**Issue by critiqalfish** [TheNoim/project-sitnu#9]
It would be really useful if you release compiled IPAs so everyone can sideload them if they have altstore or something else.

**Comment by TheNoim** [comment]
I uploaded an ipa: https://github.com/TheNoim/project-sitnu/releases/tag/1.2.0

Also look at this: https://github.com/rileytestut/AltStore/issues/229 It seems like altstore still do not support apple watch apps.

**Comment by TheNoim** [comment]
But I also uploaded a new version to TestFlight if you are interested. Should be available in a few hours with the link which you can find in the readme.

**Comment by critiqalfish** [comment]
Thank you very much.

Yes altstore does not support watch apps but i have tried to install SITNU via altstore. Sadly without success because i get an error during the installing process. I expected that so i tried installing it with Reprovision Reborn (a jailbreak tweak similar to altstore but with apple watch support) but this also gave me an error. Then i tried fakesigning it and and installing it with another tweak named Appsync Unified also without success. So i suppose there is something wrong with the app or just my phone.

I installed it with Testflight and it works like a charm so thank you for your great work. There is already a similar app to this in the appstore but with less functionality and no watch face widget, which was the point why i really wanted this app.

**Comment by TheNoim** [comment]
I am glad you like it. Maybe one day I publish this app to the app store.
